serviceName : Todo-Backend
serviceUrl : https://dennis-hartrampf-todo-backend.herokuapp.com/
serviceDescription : Implementation of the Todo-Backend (http://www.todobackend.com/) using Hexagon (https://hexagonkt.com/)
serviceLongDescription : >
  This is a sample implementation of the [Todo-Backend](http://www.todobackend.com/) using 
  [Hexagon](https://hexagonkt.com/) and Kotlin.
  The application is deployed under https://dennis-hartrampf-todo-backend.herokuapp.com/ using [Travis CI](https://travis-ci.org/).


authorName : Dennis Hartrampf
httpKeywords : Hexagon, Kotlin, Example, JVM, Web, TravisCI, Heroku

# HTTP Server
bindPort : 2010
bindAddress : 0.0.0.0
