
# Service
serviceName : Todo
serviceUrl : http://hexagonkt.com
serviceDescription : The atoms of your platform
serviceLongDescription : >
  Hexagon is a microservices library written in Kotlin. Its purpose is to ease the building of
  services (Web applications, APIs or queue consumers) that run inside a cloud platform

# HTML
cdn : http://cdnjs.cloudflare.com/ajax/libs
bootstrapVersion : "3.3.7"

authorName : Juanjo Aguililla
httpKeywords : Hexagon, Kotlin, Example, MongoDB, JVM, Web
httpGenerator : Hexagon
themeColor : "#135AA1"

twitterAccount : "@hexagon_kt"

# HTTP Server
bindPort : $PORT
bindAddress : 0.0.0.0

# Storage
database : todo
